### ISSUE TITLE
About Evaluating

### ISSUE THREAD

**Issue by VitaLemonTea1** [wzzheng/OccWorld#11]
Hi，
Thanks for your help. I just finished training with 4 x 3090. After evaluating, I see that the result has a big different from yours.
I wander if you can tell me where can I change the tokenizer settings and other hyperparameters.
Thanks!

**Comment by liuziyang123** [comment]
Hi, I have the same question.
The VQ-VAE was trained for 200 epochs on 8 v100 GPUs. The batch size is 1 for per GPU. After training I got the results in the following:
![20231218-113927](https://github.com/wzzheng/OccWorld/assets/40970363/ae77777f-c25e-4738-981d-d67d3c8360f6)
Then for the second stage, the checkpoint of VQ-VAE (epoch_200.pth) was loaded. The OccWorld was trained for another 200 epochs on 8 v100 GPUs. After training I run the `eval_metric_stp3.py` and got the final results:
![20231218-113932](https://github.com/wzzheng/OccWorld/assets/40970363/62e59566-8a62-4686-b115-ca08e8ddf2c7)
However, the result seemed to be different from that announced in the paper:
![screenshot-20231218-114551](https://github.com/wzzheng/OccWorld/assets/40970363/305de99f-8ea9-407e-b91c-87d47f47dc89)

**Comment by dk-liang** [comment]
I have the same question

**Comment by LMD0311** [comment]
I also have the Nan problem when using 4 RTX 4090 with batch 1.
When I use 4 RTX 4090 with batch 2, I avoid the nan problem, but I can't get similar results.
I find only 8 RTX 4090 works fine, any suggestions? @wzzheng

**Comment by chen-wl20** [comment]
Thank you for your interest! I'm very sorry for replying so late. I have provided the training and testing logs for the github repository code. The results maybe a bit different due to random numbers. I also provide the model used in the article and its evaluation log. Also, recommend selecting the best vqvae model for the occworld training.
