### ISSUE TITLE
Quesion about the Pose_mode

### ISSUE THREAD

**Issue by yuyang-cloud** [wzzheng/OccWorld#14]
Excellent Work and released code!
I went through the code and met an unclear question in ```dataset.py``` at [here](https://github.com/wzzheng/OccWorld/blob/65658b16669493cc3f428bc615112bb22aede8f9/dataset/dataset.py#L80C13-L80C77):
```gt_modes.append(self.nusc_infos[scene_name][idx+i]['pose_mode'])```

The ```pose_mode``` seems to be a three-dimensional vector. 
What does it mean? Could authors give an explanation? 
Thanks in advance!

**Comment by SeaBird-Go** [comment]
I also want to ask this question, what are the meanings of `rel_poses` and `gt_mode` in the pickle file? Since we don't know how to create these pickle files.

**Comment by synsin0** [comment]
same question.

**Comment by yuyang-cloud** [comment]
Hi! Is there anyone who can answer this question? 
How to generate pkl file in this [issue](https://github.com/wzzheng/OccWorld/issues/17#issue-2123058992)? What are the meanings of ```rel_poses``` and ```gt_mode```?
@wzzheng Many thanks in advance!

**Comment by chen-wl20** [comment]
Thank you very much for your attention to the repository for this job. I apologize for the late response.
Regarding the part on motion planning, we borrowed from the work of vad in the pkl file and evaluation metrics, so you can refer to [vad](https://github.com/hustvl/VAD) on how to generate pkl files.
As for pose_mode, I borrowed the gt_ego_fut_cmd from the pkl file of vad. Therefore, based on my understanding, pose predicts three possible future displacements (I believe they are left turn, straight, and right turn), and cmd is used to select the actual situation. Then, a comparison is made with the actual displacement to obtain the supervision signal.
Thank you again for your attention.

**Comment by yuyang-cloud** [comment]
Thanks for your reply!
