### ISSUE TITLE
Where to download gts?

### ISSUE THREAD

**Issue by Wangxuecheng666** [wzzheng/OccWorld#15]
Can any kind person tell me where to download the gts in Occ3D? Thank you!

**Comment by yancx8** [comment]
+1

**Comment by Wangxuecheng666** [comment]
> +1

https://drive.google.com/drive/folders/1Xarc91cNCNN3h8Vum-REbI-f0UlSf5Fc

**Comment by yancx8** [comment]
Thank you!
The nuscenes is full or mini?
And lidarseg is downloaded in www.nuscenes.org separately？The nuscenes dataset does not have lidarseg.

**Comment by chen-wl20** [comment]
> Thank you! The nuscenes is full or mini? And lidarseg is downloaded in [www.nuscenes.org](http://www.nuscenes.org) separately？The nuscenes dataset does not have lidarseg.

Thank you for your interest.For the lidarseg I think you can register and log in to the nuscenes official website [www.nuscenes.org](http://www.nuscenes.org/), and then find the downloads in nuScenes. We refer to the All dataset, but occworld actually uses the data in occ3, which can be found in https://github.com/Tsinghua-MARS-Lab/Occ3D .
![image](https://github.com/wzzheng/OccWorld/assets/83909459/ac89b7a9-2077-4344-bd55-0c4a1a450a38)
