### ISSUE TITLE
Attempts at lower versions of CUDA？

### ISSUE THREAD

**Issue by fine2copyV** [wzzheng/OccWorld#3]
The Occ project is truly great, and I am delighted to see it being open-sourced. However, I am facing a dilemma. Despite the exquisite model design and innovative conceptualization, the installation process seems ambiguous to me. Many versions appear to be too advanced. I wonder if the author has tried installing it on other slightly lower versions, such as CUDA 11.3 or others. I look forward to your reply.

**Comment by chen-wl20** [comment]
Thank you for your interest!
I have not tried other versions of CUDA, but I think it only needs to match the version of the python library to ensure consistent usage of functions.
Looking forward to your further attempts!
