### ISSUE TITLE
您好，我想问一下关于训练VQ-VAE的问题

### ISSUE THREAD

**Issue by liuziyang123** [wzzheng/OccWorld#5]
您好，感谢您们出色的工作
我想问一下第一阶段VQ-VAE的训练细节，或者是否有相关的config文件？

**Comment by SeaBird-Go** [comment]
@chen-wl20 @wzzheng ，also want to ask this question, could you provide the config to train the VQ-VAE?

BTW, in your offered `occworld.py` config, the `num_frames=15`, while the `end_frame=11`, which could cause assert error in this [line](https://github.com/wzzheng/OccWorld/blob/543111aca74baba6a3fbf7053bdcd84046f83e6a/model/TransVQVAE.py#L106C22-L106C22), could you help me to solve this?

Thanks in advance.

**Comment by chen-wl20** [comment]
Thank you for your interest!
We have update the code and the config files just now.
Thank you for your continued attention. Feel free to **star** our project and follow subsequent updates!

**Comment by liuziyang123** [comment]
Many thanks.
