### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by VitaLemonTea1** [wzzheng/OccWorld#6]
Hi，

Thanks for releasing code. Do I need to download the whole nuscene dataset, or just need Lidarseg.

Thanks!

**Comment by chen-wl20** [comment]
Thank you for your interest!
I possess the complete dataset, yet it seems that all I require is the gts from Occ3D.

**Comment by chen-wl20** [comment]
Thank you for your attention!
Occ3D is a dataset focused on 3D occupancy. The file structure is as follows, and you can easily load the .npz files using numpy for your applications. For more details please follow the Occ3d page.
├── gts  
    |  ├── [scene_name]
    |   |   ├── [frame_token]
    |   |   |   └── labels.npz

**Comment by VitaLemonTea1** [comment]
Thanks，I check the webpage and download it！
After running train.py , it got another problem, AttributeError: 'ConfigDict' object has no attribute 'load_from'.
I have checked the issues of mmengine, but there is no help. I wander if you can help me fix it.

**Comment by chen-wl20** [comment]
Thank you for your continued attention!
This bug can be solved by adding the vqvae model path using load_from in the config file. We have update the code and the config files just now, which may contribute to your problem!

**Comment by VitaLemonTea1** [comment]
I read the paper and see that you and your colleges trained the model with 8x4090.
Could you please tell me how long you spend on training.
